### ISSUE TITLE
EB: create aws resources with custom Names (lb, ASG, LC ..)

### ISSUE THREAD

**Issue by adil-bouchaara** [awsdocs/elastic-beanstalk-samples#104]
hello,

my case is that I want to create a web environment with custom names that I specify for the Load balancer, Autoscaling group, launch configuration since I want to use that in filtering for monitoring.
for the moment EB it generates those names with ids.

**Comment by dankhen** [comment]
Hi @adil-bouchaara ,
Thanks for writing to us. This repo is for examples maintained by documentation writers. Your question is more of a support case - is something possible or not with Elastic Beanstalk. Please try to ask this question on [our forum](https://forums.aws.amazon.com/forum.jspa?forumID=86), or contact the support team. It it turns out that it's possible to do what you're asking for, the support people will let us know and we can add an example here.
Thanks!
