### ISSUE TITLE
chef on beanstalk

### ISSUE THREAD

**Issue by cbanciu667** [awsdocs/elastic-beanstalk-samples#60]
Pls include my chef integration with Beanstalk Windows instances:
cbanciu667/cos_beanstalk/ChefClient.config.yaml

I also have an example with Oracle Client installation

**Comment by dankhen** [comment]
Hi,

Thanks for the submission. Please include a long comment at the top, with:
- The goal of this config file. What functionality does it add to the instances?
- A top-level explanation of the solution. How does it achieve the goal?
- Anything that a customer using this file has to set or do (in addition to including the file in the source bundle).
- A list of the Beanstalk .NET configurations that this works on.
- Your HitHub name as the author.

Please also change the file name to `ChefClient.config`.

Does this works on the Beanstalk .NET platform as-is, and doesn't require anything in the source bundle in addition to the config file? Or is this supposed to be an addition to an application's source files? I understand that the script syncs down an S3 bucket, but:
- I see some variables used in the commands at the bottom - I am not clear where they are set.
- Where does `C:\opscode\chef\bin\chef-client.bat` come from?

Once we've clarified everything, I will ask you to please re-submit the result as a pull request, adding it into the location where you think it belongs. I'm assuming this should go into `https://github.com/awslabs/elastic-beanstalk-samples/tree/master/configuration-files/community-provided/instance-configuration`.

**Comment by dankhen** [comment]
Hi @cbanciu667,
Would you still like to follow up on this submission?

**Comment by cbanciu667** [comment]
Hi @dankhen ,

- The goal of this chef-client config is to have chef client installed, configured and converging on Beanstalk Windows instances. There is also an additional cmd script/policy to cleanup the chef node when the instance is shutdown (although this should be used: https://aws.amazon.com/blogs/apn/automatically-delete-terminated-instances-in-chef-server-with-aws-lambda-and-cloudwatch-events/).

- This solution works by using a combination of one S3 bucket, one powershell script, one cmd script and some Beanstalk environment variables that could be pushed also via CF templates if needed. The most important are the S3 bucket and the variables.

- Someone using this config must define an S3 bucket containing the desired chef client msi plus the validation.pem file used to register the chef node. 
Regarding the shutdown detection mechanism/script, i have one special cookbook that contains another PS script that allows the policy registration. That one can be found here:
https://github.com/cbanciu667/cos_windows_base/blob/master/templates/default/UserRights.ps1.erb
Otherwise the shutdown part can be removed to simplify the entire config run and the alternative can be used instead - see my link from first comment above.

- This config works on any Beanstalk windows 2012/2016 environment and does not depends on any Windows services or components other than PowerShell.

- Author name is Cosmin Banciu

- name changed 

- the variables from the script are in fact Beanstalk Environment variables passed in the 01_chefcl_command. so the order would be: create files/folders required by the mechanism and
run the commands with parameter waitAfterCompletion: 0 to have the entire mechanism faster.
The commands are also included in a container_commands section so they run right at the end of the entire Beanstalk Deployment process.

**Comment by dankhen** [comment]
@cbanciu667,
It looks to me that this example has more elements than just this .config file. It's very useful, but doesn't stand on its own and might be hard to use without all the other elements and a step-by-step tutorial.

To make your contribution more valuable to the community, I suggest we change the approach. Instead of submitting a PR to include this .config file in our repo in isolation, turn this into an example application. Create a repo for it in your account, and include all the necessary elements:
- A `readme.md` with detailed documentation. Provide the info from your last comment here, and a step-by-step tutorial to creating a working application.
- This config file, `ChefClient.config`.
- An example chef client msi.
- The `validation.pem` file used to register the chef node.

We can then feature your repo at the front page of our repo, as a link from [our repo's readme](https://github.com/awsdocs/elastic-beanstalk-samples) to a community-provided sample application.

A good example to such a contribution is [go-beanstalk-gin](https://github.com/sudo-suhas/go-beanstalk-gin) by @sudo-suhas, which you can see linked at the end of the readme.

**Comment by cbanciu667** [comment]
Hi @dankhen ,

I totally agree. I will create the new repo and pot the link.

**Comment by ebattalio** [comment]
Closing. 

@cbanciu667 If you do create the isolated example, please reopen with info. Thanks!
