### ISSUE TITLE
SQS with https redirect (Rails/Puma)

### ISSUE THREAD

**Issue by exige81** [awsdocs/elastic-beanstalk-samples#64]
Running RoR 5.1 with the following config:
https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/security-configuration/https-redirect/ruby-puma/https-redirect-ruby-puma.config

I was unable to get the worker tier to consume jobs from SQS.  (Error logs show a 301 redirect).

Per [worker environments documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html), SQS sends a POST request to http://localhost/ 

Because of this I believe the current config is redirecting the SQS post.

To fix the issue, modified the config as follows:
```
location / {
             set $redirect 0;
             if ($http_x_forwarded_proto != "https") {
               set $redirect 1;
             }
             if ($http_user_agent ~* "ELB-HealthChecker") {
               set $redirect 0;
             }
             if ($http_user_agent ~* "aws-sqsd") {
               set $redirect 0;
             }
             if ($redirect = 1) {
               return 301 https://$host$request_uri;
} 
```

I was able to solve my issue by checking for the SQS user agent.  Wonder if this should be included  in the sample config files by default?

**Comment by dankhen** [comment]
Hi @exige81 ,
You are right - the SQS daemon on a worker environment sends a POST request to http://localhost/ on port 80.
This config example, as stated in its comment, is for environments that are configured to support HTTPS. I am curious why you wanted to configure a worker environment to support HTTPS.

**Comment by exige81** [comment]
Hi @dankhen,
I don't really want to configure my worker environment to support HTTPS, however I deploy both my web and worker environments from the same source.

Ideally, it would be nice if .ebextensions config files could be namespaced to a specific environment so that I could ignore the HTTPS config for my worker environment, but there doesn't seem to be a way to set environment specifc configs at this time.

If you're aware of a better way to handle this, I'm open to suggestions.

**Comment by dankhen** [comment]
I'll discuss with our service team and follow up. Thanks!

**Comment by dankhen** [comment]
@exige81 ,
After much deliberation on the service team, we'd like to communicate our thoughts about your solution, modifying the example, and configuration file environment-scoping.

For your needs, you did the right thing. From the narrow standpoint of using the same .ebextensions for both web and worker environments, your change indeed takes care of doing the HTTPS redirection only on the web server, and dropping it on the worker tier.

However, the broader notion of using the same code base (the same source bundle) for deploying multiple environments, especially for multiple tiers, isn't a supported Elastic Beanstalk scenario. Since we don't support and test it, it may or may not work, and we can't recommend it. Therefore, we wouldn't want to publish an example that would imply it's a supported or recommended use case. We have to decline to change the example.

For the same reason, while your idea of environment-scoping for configuration files would be good if sharing configuration files was supported, we're not likely to pursue it for the current supported scenarios.

Thanks for posting these ideas!

**Comment by CaseJnr** [comment]
@exige81 did you ever find a solution to this.

**Comment by exige81** [comment]
@CaseJnr the workaround is to modify the `https-redirect-ruby-puma.config` example as shown in the first post of this issue.   This prevents the redirect if the user agent is from `aws-sqsd` the which is the SQS daemon
