### ISSUE TITLE
Update elastic beanstalk rds-ssl-java.config for use with new certs

### ISSUE THREAD

**Issue by alexmherrmann** [awsdocs/elastic-beanstalk-samples#99]
The rds-ssl-java.config is still using the 2015 cert. With the deprecation underway, I think both should be added in, and eventually stop adding the 2015 cert.

Happy to do it when I get some free time as it's a little time-consuming to make sure everything is working properly with the uploading of a new version, downloading logs, etc.

**Comment by dankhen** [comment]
@alexmherrmann , thanks for pointing this out!
Rather than risking using discontinued certificates in the example, I'll go ahead and update it with the 2019 certs (sorry, I don't have the bandwidth to verify - I'll assume that the RDS team has published correct certs).
We'd still much appreciate if you could get to verifying it at some point - that'll be awesome. TIA!
